# Creating a product landing page
# yao run neo.html.Page 帮我生成一个宠物详情页
name: Generate pet detail page
use: html
connector: gpt-3_5-turbo
process: studio.html.Page
args:
  - name: name
    type: String
    description: The generated HTML code
    required: true
    default: ""

  - name: html
    type: String
    description: The generated HTML code
    required: true
    default: ""

  - name: css
    type: String
    description: The generated CSS code
    required: true
    default: ""

  - name: js
    type: String
    description: The generated Javascirpt code
    required: true
    default: ""

actions:
  - name: Redirect to the generated page
    type: "Common.historyPush"
    payload:
      pathname: "{{ iframe }}"
      public: false

prepare:
  before: studio.html.PageBefore
  after: studio.html.PageAfter
  option:
    temperature: 0.6

  prompts:
    - role: system
      content: "{{ template }}"

    - role: system
      content: "{{ explain }}"

    - role: system
      content: |
        - Please create a webpage based on my description using HTML, CSS, and JS, and reply to me in the format of the template I provided you.
        - Reply to me with a message in JSON format only: {"name": "<Replace it with the test data generated by the template>", "html": "<Replace it with the test data generated by the template>",  "css": "<Replace it with the test data generated by the template>", "js": "<Replace it with the test data generated by the template>"}
        - The fields "name", "html", "css", and "js" are required and must be included.
        - Do not explain your answer, and do not use punctuation!

description: |
  Generate pet detail page

optional:
  autopilot: true
