# Creating a product landing page
# yao run neo.image.Product 帮我生成一个宠物海报
name: Generate pet photo
use: image
connector: gpt-3_5-turbo
process: scripts.image.Draw
args:
  - name: prompt
    type: String
    description: The SD prompt
    required: true
    default: ""

  - name: width
    type: Integer
    description: The image width
    required: true
    default: ""

  - name: height
    type: Integer
    description: The image height
    required: true
    default: ""

prepare:
  before: scripts.image.DrawBefore
  after: scripts.image.DrawAfter
  option:
    temperature: 0.6

  prompts:
    - role: system
      content: "{{ template }}"

    - role: system
      content: "{{ explain }}"

    - role: system
      content: |
        - Translate the given question into English.
        - Extract as much "Summary" of my question and the history, as possible without losing valid information.
        - If there is "Width" information in my question, help me extract it and convert it into pixels and keep the type as Integer.
        - If there is "Height" information in my question, help me extract it and convert it into pixels and keep the type as Integer.
        - Reply to me with a message in JSON format only: {"prompt": "<Replace it with the test data generated by the template>", "width": "<Replace it with the test data generated by the template>",  "height": "<Replace it with the test data generated by the template>"}
        - The fields "prompt" are required and must be included.
        - Do not explain your answer, and do not use punctuation!

description: |
  Generate pet photo

optional:
  autopilot: true
